const strengths=[2.5,5,7.5,10,12.5,15];let state=loadState();
const $=id=>document.getElementById(id);const fmt=n=>(Math.round((Number(n)||0)*100)/100).toLocaleString('de-DE');
function fillSelect(sel){sel.innerHTML=strengths.map(v=>`<option value="${v}">${fmt(v)} mg</option>`).join('')}
fillSelect($('penStrength'));fillSelect($('plannerStrength'));
function render(){const pen=state.pen;let remaining=pen?pen.remaining:0,total=pen?pen.total:0,used=Math.max(0,total-remaining),pct=total?Math.max(0,Math.min(100,remaining/total*100)):0;$('activePenTitle').textContent=pen?`${fmt(total)} mg Pen`:'Noch kein Pen';$('activePenSub').textContent=pen?`Gestartet am ${new Date(pen.startedAt).toLocaleDateString('de-DE')}`:'Starte einen neuen Pen.';$('remainingMg').textContent=fmt(remaining);$('usedMg').textContent=fmt(used);$('ringText').textContent=Math.round(pct)+'%';$('ring').style.background=`conic-gradient(var(--primary) ${pct*3.6}deg,#ded6ff 0deg)`;$('meterFill').style.width=pct+'%';const last=state.history[0];$('lastDose').textContent=last?fmt(last.amount):'–';$('historyList').innerHTML=state.history.length?state.history.map((h,i)=>`<div class="history-item"><div><strong>${fmt(h.amount)} mg entnommen</strong><small>${new Date(h.date).toLocaleString('de-DE')}${h.note?' · '+h.note:''}</small></div><div><strong>${fmt(h.remaining)} mg</strong><small>Rest</small></div></div>`).join(''):'<p class="muted">Noch keine Entnahmen gespeichert.</p>';plan()}
function plan(){const total=Number($('plannerStrength').value||0),dose=Number($('plannerDose').value||0);if(!dose){$('plannerResult').textContent='–';return}const full=Math.floor(total/dose),rest=+(total-full*dose).toFixed(2);$('plannerResult').textContent=`${full}× vollständig, ${fmt(rest)} mg Rest`}
$('newPenBtn').onclick=()=>$('penDialog').showModal();$('doseBtn').onclick=()=>{if(!state.pen){$('penDialog').showModal();return}$('doseDialog').showModal()};$('settingsBtn').onclick=()=>$('settingsDialog').showModal();
$('savePen').onclick=e=>{e.preventDefault();const selected=Number($('penStrength').value),custom=Number($('customTotal').value),total=custom>0?custom:selected;state={pen:{total,remaining:total,startedAt:new Date().toISOString()},history:[]};saveState(state);$('penDialog').close();render()};
$('saveDose').onclick=e=>{e.preventDefault();const amount=Number($('doseAmount').value);if(!state.pen||amount<=0)return;const remaining=+(Math.max(0,state.pen.remaining-amount)).toFixed(2);state.pen.remaining=remaining;state.history.unshift({amount,remaining,note:$('doseNote').value.trim(),date:new Date().toISOString()});$('doseAmount').value='';$('doseNote').value='';saveState(state);$('doseDialog').close();render()};
$('clearHistoryBtn').onclick=()=>{if(confirm('Verlauf wirklich löschen?')){state.history=[];saveState(state);render()}};$('plannerStrength').onchange=plan;$('plannerDose').oninput=plan;$('exportBtn').onclick=()=>exportState(state);$('importFile').onchange=async e=>{const f=e.target.files[0];if(!f)return;state=JSON.parse(await f.text());saveState(state);render();$('settingsDialog').close()};
if('serviceWorker'in navigator){navigator.serviceWorker.register('./service-worker.js')}render();
