const strengths=[2.5,5,7.5,10,12.5,15];
const $=s=>document.querySelector(s); const $$=s=>document.querySelectorAll(s);
const fmt=n=>Number(n||0).toLocaleString('de-DE',{maximumFractionDigits:2});
const today=()=>new Date().toLocaleString('de-DE',{day:'2-digit',month:'2-digit',hour:'2-digit',minute:'2-digit'});
let state=JSON.parse(localStorage.getItem('mounjaro.v4')||'null')||{pens:[],activePenId:null,history:[],theme:'dark'};
function save(){localStorage.setItem('mounjaro.v4',JSON.stringify(state));render();}
function activePen(){return state.pens.find(p=>p.id===state.activePenId)||state.pens[0];}
function setActive(id){state.activePenId=id;save();}
function createPen(strength,name=''){const id=crypto.randomUUID();state.pens.unshift({id,name:name||`Pen ${fmt(strength)} mg`,strength:Number(strength),rest:Number(strength),created:new Date().toISOString()});state.activePenId=id;save();}
function dose(amount,note=''){const p=activePen(); if(!p){alert('Bitte zuerst einen Pen anlegen.');return} amount=Number(amount); if(!amount||amount<=0){alert('Bitte eine gültige Menge eingeben.');return} if(amount>p.rest+0.0001&&!confirm('Die Menge ist größer als die Restmenge. Trotzdem speichern?'))return; p.rest=Math.max(0,+(p.rest-amount).toFixed(3)); state.history.unshift({id:crypto.randomUUID(),penId:p.id,penName:p.name,amount,rest:p.rest,note,date:new Date().toISOString()}); save();}
function deleteHistory(id){const h=state.history.find(x=>x.id===id); if(!h)return; const p=state.pens.find(x=>x.id===h.penId); if(p)p.rest=Math.min(p.strength,+(p.rest+h.amount).toFixed(3)); state.history=state.history.filter(x=>x.id!==id); save();}
function deletePen(id){if(!confirm('Pen löschen? Der Verlauf bleibt erhalten.'))return;state.pens=state.pens.filter(p=>p.id!==id); if(state.activePenId===id)state.activePenId=state.pens[0]?.id||null; save();}
function pct(p){return p?Math.max(0,Math.min(100,p.rest/p.strength*100)):0}
function renderDashboard(){const p=activePen(); const used=p?Math.max(0,p.strength-p.rest):0; $('#activePenTitle').textContent=p?p.name:'Kein Pen'; $('#activePenSubtitle').textContent=p?`${fmt(p.strength)} mg Gesamtmenge`:'Tippe auf „Neuer Pen“.'; $('#restValue').textContent=p?fmt(p.rest):'0'; $('#usedValue').textContent=`${fmt(used)} mg`; const last=state.history[0]; $('#lastDoseValue').textContent=last?`${fmt(last.amount)} mg`:'–'; const pr=pct(p); $('#penFill').style.width=pr+'%'; $('#ringProgress').style.strokeDashoffset=314-(314*pr/100); renderPlanner();}
function renderPens(){const box=$('#penList'); if(!state.pens.length){box.innerHTML='<div class="item"><div><strong>Noch kein Pen</strong><p>Lege deinen ersten Pen an.</p></div></div>';return} box.innerHTML=state.pens.map(p=>`<div class="item"><div><strong>${p.id===state.activePenId?'✓ ':''}${p.name}</strong><p>${fmt(p.rest)} von ${fmt(p.strength)} mg übrig · ${fmt(pct(p))}%</p></div><div class="item-actions"><button onclick="setActive('${p.id}')">Aktiv</button><button onclick="deletePen('${p.id}')">Löschen</button></div></div>`).join('');}
function renderHistory(){const box=$('#historyList'); if(!state.history.length){box.innerHTML='<div class="item"><div><strong>Kein Verlauf</strong><p>Entnahmen erscheinen hier automatisch.</p></div></div>';return} box.innerHTML=state.history.map(h=>`<div class="item"><div><strong>${fmt(h.amount)} mg</strong><p>${new Date(h.date).toLocaleString('de-DE')} · Rest: ${fmt(h.rest)} mg<br>${h.note? h.note+' · ':''}${h.penName}</p></div><div class="item-actions"><button onclick="deleteHistory('${h.id}')">↶</button></div></div>`).join('');}
function renderPlanner(){const p=activePen(); const d=Number(($('#plannerDose').value||'').replace(',','.')); if(!p){$('#plannerResult').textContent='Lege zuerst einen Pen an.';return} if(!d||d<=0){$('#plannerResult').textContent='Gib eine Wunschdosis ein.';return} const full=Math.floor((p.rest+1e-9)/d); const rem=+(p.rest-full*d).toFixed(3); $('#plannerResult').textContent=`Mit ${fmt(d)} mg sind ${full} vollständige Anwendungen möglich. Danach bleiben ${fmt(rem)} mg übrig.`;}
function render(){document.body.classList.toggle('light',state.theme==='light'); renderDashboard(); renderPens(); renderHistory();}
$$('.tab').forEach(b=>b.addEventListener('click',()=>{$$('.tab,.view').forEach(x=>x.classList.remove('active'));b.classList.add('active');$('#'+b.dataset.view).classList.add('active')}));
$('#newPenBtn').onclick=$('#newPenBtn2').onclick=()=>$('#penDialog').showModal(); $('#openDoseBtn').onclick=()=> activePen()?$('#doseDialog').showModal():$('#penDialog').showModal();
$('#penForm').addEventListener('submit',e=>{e.preventDefault(); createPen($('#penStrength').value,$('#penName').value.trim()); $('#penName').value=''; $('#penDialog').close();});
$('#doseForm').addEventListener('submit',e=>{e.preventDefault(); dose(($('#doseAmount').value||'').replace(',','.'),$('#doseNote').value.trim()); $('#doseAmount').value=''; $('#doseNote').value=''; $('#doseDialog').close();});
$('#plannerDose').addEventListener('input',renderPlanner); $('#themeBtn').onclick=()=>{state.theme=state.theme==='light'?'dark':'light';save()};
$('#clearHistoryBtn').onclick=()=>{if(confirm('Verlauf wirklich leeren?')){state.history=[];save();}}; $('#resetAllBtn').onclick=()=>{if(confirm('Alle Daten löschen?')){state={pens:[],activePenId:null,history:[],theme:state.theme};save();}};
$('#exportBtn').onclick=()=>{const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([JSON.stringify(state,null,2)],{type:'application/json'}));a.download='mounjaro-backup.json';a.click();};
$('#importInput').onchange=e=>{const f=e.target.files[0]; if(!f)return; const r=new FileReader(); r.onload=()=>{try{state=JSON.parse(r.result);save()}catch{alert('Import fehlgeschlagen.')}}; r.readAsText(f);};
if(!state.pens.length) createPen(10,'Mein erster Pen'); else render();
if('serviceWorker' in navigator) navigator.serviceWorker.register('service-worker.js');
